'use client';
import {useEffect,useState} from 'react';
const CORE=['DSA','Java','JVM Performance','System Design','Distributed Systems','AI Engineering','Recognition'];
const fmt=(v?:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';
const hours=(m:number)=>(m/60).toFixed(1)+'h';
export default function Phase2(){
 const[reviews,setReviews]=useState<any[]>([]),[projects,setProjects]=useState<any[]>([]),[week,setWeek]=useState<any>(null),[skills,setSkills]=useState(CORE),[error,setError]=useState(false);
 const[rSkill,setRSkill]=useState('DSA'),[topic,setTopic]=useState(''),[due,setDue]=useState('');
 const[pName,setPName]=useState(''),[pSkill,setPSkill]=useState('DSA'),[pOutcome,setPOutcome]=useState(''),[pRepo,setPRepo]=useState(''),[pTarget,setPTarget]=useState('');
 const[wins,setWins]=useState(''),[gaps,setGaps]=useState(''),[next,setNext]=useState(''),[rating,setRating]=useState(7),[saved,setSaved]=useState(false);
 const load=async()=>{try{const [r,p,w,s]=await Promise.all([fetch('/api/phase2/reviews',{cache:'no-store'}),fetch('/api/phase2/projects',{cache:'no-store'}),fetch('/api/phase2/weekly-review',{cache:'no-store'}),fetch('/api/skills',{cache:'no-store'})]);if(!r.ok||!p.ok||!w.ok||!s.ok)throw new Error();setReviews(await r.json());setProjects(await p.json());setWeek(await w.json());const c=await s.json();setSkills([...CORE,...c.map((x:any)=>x.name)]);const wr=(await fetch('/api/phase2/weekly-review',{cache:'no-store'})).json();setWeek(await wr);}catch{setError(true)}};useEffect(()=>{load()},[]);
 const addReview=async()=>{if(!topic.trim())return;const r=await fetch('/api/phase2/reviews',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({skillName:rSkill,topic,dueDate:due||null})});if(r.ok){setTopic('');setDue('');setReviews(await (await fetch('/api/phase2/reviews')).json())}else setError(true)};
 const complete=async(id:number)=>{const r=await fetch(`/api/phase2/reviews/${id}/complete`,{method:'POST'});if(r.ok)setReviews(x=>x.filter(v=>v.id!==id));else setError(true)};
 const snooze=async(id:number)=>{const d=new Date();d.setDate(d.getDate()+7);const iso=d.toISOString().slice(0,10);const r=await fetch(`/api/phase2/reviews/${id}/snooze`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({dueDate:iso})});if(r.ok)setReviews(await (await fetch('/api/phase2/reviews')).json());else setError(true)};
 const addProject=async()=>{if(!pName.trim())return;const r=await fetch('/api/phase2/projects',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:pName,skillName:pSkill,outcome:pOutcome,repoUrl:pRepo,targetDate:pTarget||null})});if(r.ok){setPName('');setPOutcome('');setPRepo('');setPTarget('');setProjects(await (await fetch('/api/phase2/projects')).json())}else setError(true)};
 const status=async(id:number,value:string)=>{const r=await fetch(`/api/phase2/projects/${id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({status:value})});if(r.ok)setProjects(await (await fetch('/api/phase2/projects')).json());else setError(true)};
 const delProject=async(id:number)=>{if(!confirm('Delete this project?'))return;const r=await fetch(`/api/phase2/projects/${id}`,{method:'DELETE'});if(r.ok)setProjects(x=>x.filter(p=>p.id!==id));else setError(true)};
 const saveReview=async()=>{const r=await fetch('/api/phase2/weekly-review',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({wins,gaps,nextWeek:next,rating})});if(r.ok){setSaved(true);setTimeout(()=>setSaved(false),2000);setWeek(await (await fetch('/api/phase2/weekly-review')).json())}else setError(true)};
 useEffect(()=>{const existing=week?.review?.[0];if(existing){setWins(existing.wins||'');setGaps(existing.gaps||'');setNext(existing.next_week||'');setRating(existing.rating||7)}},[week]);
 if(!week)return <main><header className="topbar"><div><div className="eyebrow">PHASE 2</div><h1>Execution Hub</h1><p>Review · Projects · Weekly review</p></div><a className="back-link" href="/learning">← Learning HQ</a></header>{error&&<div className="notice">Backend unavailable.</div>}<section className="card"><p className="muted">Loading…</p></section></main>;
 return <main><header className="topbar"><div><div className="eyebrow">PHASE 2 · EXECUTION</div><h1>Execution Hub</h1><p>Turn learning into retention, projects and weekly course correction.</p></div><a className="back-link" href="/learning">← Learning HQ</a></header>{error&&<div className="notice">Some data could not be saved or loaded.</div>}
 <section className="dsa-stats"><div className="metric"><span>This week</span><strong>{hours(Number(week.minutes||0))}</strong><small>{week.sessions||0} study sessions</small></div><div className="metric"><span>Tasks completed</span><strong>{week.completedTasks||0}</strong><small>since Monday</small></div><div className="metric"><span>Reviews due</span><strong>{week.dueReviews||0}</strong><small>retention queue</small></div><div className="metric"><span>Active projects</span><strong>{projects.filter(p=>p.status!=='DONE').length}</strong><small>skill-connected builds</small></div></section>
 <section className="card review-card"><div className="section-head"><div><h2>Review & revisit queue</h2><p className="muted">Revisit items created from journal notes, plus anything you add manually.</p></div><strong>{reviews.length} open</strong></div><div className="goal-form"><select value={rSkill} onChange={e=>setRSkill(e.target.value)}>{skills.map(s=><option key={s}>{s}</option>)}</select><input value={topic} onChange={e=>setTopic(e.target.value)} placeholder="Topic to revisit · e.g. Kafka consumer rebalancing"/><input type="date" value={due} onChange={e=>setDue(e.target.value)}/><button onClick={addReview} disabled={!topic.trim()}>＋ Add review</button></div><div className="review-list">{reviews.map(x=><div className="goal" key={x.id}><div className="goal-head"><div><b>{x.skill_name}</b><span>{x.topic}</span></div><span className="badge">Due {fmt(x.due_date)}</span></div><div className="goal-meta"><span>{x.source_type}</span>{x.due_date<=new Date().toISOString().slice(0,10)&&<strong>Due now</strong>}</div><div className="review-actions"><button onClick={()=>complete(x.id)}>✓ Mark reviewed</button><button onClick={()=>snooze(x.id)}>Snooze 7 days</button></div></div>)}{reviews.length===0&&<p className="empty-state">Nothing due. Keep logging journal revisit items and the queue will build automatically.</p>}</div></section>
 <section className="card"><div className="section-head"><div><h2>Projects connected to skills</h2><p className="muted">Every serious skill should produce evidence: a build, repo, demo or measurable outcome.</p></div></div><div className="goal-form"><input value={pName} onChange={e=>setPName(e.target.value)} placeholder="Project name"/><select value={pSkill} onChange={e=>setPSkill(e.target.value)}>{skills.map(s=><option key={s}>{s}</option>)}</select><input value={pOutcome} onChange={e=>setPOutcome(e.target.value)} placeholder="Outcome / evidence"/><input value={pRepo} onChange={e=>setPRepo(e.target.value)} placeholder="Repo / demo URL"/><input type="date" value={pTarget} onChange={e=>setPTarget(e.target.value)}/><button onClick={addProject} disabled={!pName.trim()}>＋ Add project</button></div><div className="project-list">{projects.map(p=><article className="project" key={p.id}><div className="goal-head"><div><b>{p.name}</b><span>{p.skill_name} · {p.outcome||'No outcome defined'}</span></div><button className="remove-skill" onClick={()=>delProject(p.id)}>Delete</button></div><div className="goal-meta">{p.target_date&&<span>Target {fmt(p.target_date)}</span>}{p.repo_url&&<a href={p.repo_url} target="_blank" rel="noreferrer">Open repo ↗</a>}</div><select value={p.status} onChange={e=>status(p.id,e.target.value)}><option>PLANNED</option><option>ACTIVE</option><option>BLOCKED</option><option>DONE</option></select></article>)}{projects.length===0&&<p className="empty-state">No projects yet. Add one and connect it to a skill.</p>}</div></section>
 <section className="card"><div className="section-head"><div><h2>Weekly review</h2><p className="muted">Close the loop every Monday: what worked, what failed, and what changes next.</p></div><strong>Week of {fmt(week.weekStart)}</strong></div><div className="weekly-review-grid"><div><label>Wins</label><textarea value={wins} onChange={e=>setWins(e.target.value)} placeholder="What moved forward? What are you proud of?"/></div><div><label>Gaps</label><textarea value={gaps} onChange={e=>setGaps(e.target.value)} placeholder="Where did you underperform or get stuck?"/></div><div><label>Next week</label><textarea value={next} onChange={e=>setNext(e.target.value)} placeholder="What are the 1–3 highest-leverage changes?"/></div><div><label>Self-rating: {rating}/10</label><input type="range" min="0" max="10" value={rating} onChange={e=>setRating(Number(e.target.value))}/></div><button onClick={saveReview}>{saved?'Saved ✓':'Save weekly review'}</button></div></section>
 <footer>Phase 2 · Review → Build → Reflect → Adjust</footer></main>;
}
