'use client';
import { useEffect, useMemo, useState } from 'react';

const CORE=['DSA','Java','JVM Performance','System Design','Distributed Systems','AI Engineering','Recognition'];
type SkillStat={skill:string;minutes:number;sessions:number;last_studied?:string};
type Activity={date:string;minutes:number};
type Goal={id:number;skill_name:string;target_outcome:string;deadline?:string;weekly_minutes:number};
type Journal={id:number;journal_date:string;skill_name:string;learned?:string;built?:string;difficult?:string;revisit?:string;resources?:string};
const hours=(m:number)=>`${(m/60).toFixed(1)}h`;
const fmtDate=(v?:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';

export default function Learning(){
 const[data,setData]=useState<any>(null);const[goals,setGoals]=useState<Goal[]>([]);const[journal,setJournal]=useState<Journal[]>([]);const[skills,setSkills]=useState<string[]>(CORE);const[error,setError]=useState(false);
 const[goalSkill,setGoalSkill]=useState('DSA');const[outcome,setOutcome]=useState('');const[deadline,setDeadline]=useState('');const[weekly,setWeekly]=useState(120);const[savingGoal,setSavingGoal]=useState(false);
 const[jSkill,setJSkill]=useState('DSA');const[jLearned,setJLearned]=useState('');const[jBuilt,setJBuilt]=useState('');const[jHard,setJHard]=useState('');const[jRevisit,setJRevisit]=useState('');const[jResources,setJResources]=useState('');const[savingJournal,setSavingJournal]=useState(false);
 const load=async()=>{try{const [d,g,j,s]=await Promise.all([fetch('/api/learning/dashboard',{cache:'no-store'}),fetch('/api/learning/goals',{cache:'no-store'}),fetch('/api/learning/journal',{cache:'no-store'}),fetch('/api/skills',{cache:'no-store'})]);if(!d.ok||!g.ok||!j.ok||!s.ok)throw new Error();setData(await d.json());setGoals(await g.json());setJournal(await j.json());const custom=await s.json();setSkills([...CORE,...custom.map((x:any)=>x.name)]);}catch{setError(true)}};
 useEffect(()=>{load()},[]);
 const activity=useMemo(()=>{const map=new Map((data?.activity??[]).map((x:Activity)=>[x.date,x.minutes]));const end=new Date();return Array.from({length:30},(_,i)=>{const d=new Date(end);d.setDate(end.getDate()-29+i);const key=d.toISOString().slice(0,10);return{date:key,minutes:Number(map.get(key)||0)}})},[data]);
 const maxActivity=Math.max(1,...activity.map(x=>x.minutes));
 const growth=useMemo(()=>{const rows=data?.growth??[];const map=new Map<string,Map<string,number>>();for(const r of rows){const d=new Date(`${r.date}T00:00:00`);d.setDate(d.getDate()-((d.getDay()+6)%7));const key=d.toISOString().slice(0,10);if(!map.has(key))map.set(key,new Map());map.get(key)!.set(r.skill,(map.get(key)!.get(r.skill)||0)+Number(r.minutes));}return [...map.entries()].sort((a,b)=>a[0].localeCompare(b[0])).slice(-8)},[data]);
 const stats=(data?.bySkill??[]) as SkillStat[];const weekStats=(data?.weekBySkill??[]) as {skill:string;minutes:number}[];const week=Number(data?.weekMinutes||0),month=Number(data?.monthMinutes||0),total=Number(data?.totalMinutes||0);const best=data?.bestDay?.[0];
 const addGoal=async()=>{if(!outcome.trim())return;setSavingGoal(true);try{const r=await fetch('/api/learning/goals',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({skillName:goalSkill,targetOutcome:outcome,deadline:deadline||null,weeklyMinutes:Number(weekly)})});if(!r.ok)throw new Error();setOutcome('');setDeadline('');setWeekly(120);setGoals(await (await fetch('/api/learning/goals',{cache:'no-store'})).json());}catch{setError(true)}finally{setSavingGoal(false)}};
 const deleteGoal=async(id:number)=>{if(!confirm('Delete this goal?'))return;const r=await fetch(`/api/learning/goals/${id}`,{method:'DELETE'});if(r.ok)setGoals(x=>x.filter(g=>g.id!==id));else setError(true)};
 const addJournal=async()=>{setSavingJournal(true);try{const r=await fetch('/api/learning/journal',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({skillName:jSkill,learned:jLearned,built:jBuilt,difficult:jHard,revisit:jRevisit,resources:jResources})});if(!r.ok)throw new Error();setJournal(await (await fetch('/api/learning/journal',{cache:'no-store'})).json());setJLearned('');setJBuilt('');setJHard('');setJRevisit('');setJResources('');}catch{setError(true)}finally{setSavingJournal(false)}};
 if(!data)return <main><header className="topbar"><div><div className="eyebrow">LEARNING INTELLIGENCE</div><h1>Learning HQ</h1><p>Phase 1 · effort, skills, goals and reflection</p></div><a className="back-link" href="/">← Tracker</a></header>{error&&<div className="notice">Backend unavailable. Start the Spring Boot API and refresh.</div>}<section className="card"><p className="muted">Loading learning data…</p></section></main>;
 return <main>
 <header className="topbar"><div><div className="eyebrow">LEARNING INTELLIGENCE</div><h1>Learning HQ</h1><p>One place for effort, skill growth, goals and your learning journal.</p></div><a className="back-link" href="/">← Tracker</a></header>
 {error&&<div className="notice">Some learning data could not be loaded.</div>}
 <section className="scorecard"><div className="score"><span>Total study time</span><strong>{hours(total)}</strong><small>{data.sessionCount} sessions</small></div><div className="score"><span>This week</span><strong>{hours(week)}</strong><small>target {hours(data.weeklyTargetMinutes)}</small><div className="bar"><i style={{width:`${Math.min(100,week/data.weeklyTargetMinutes*100)}%`}}/></div></div><div className="score"><span>This month</span><strong>{hours(month)}</strong><small>all tracked skills</small></div><div className="score"><span>Current streak</span><strong>{data.streak}d</strong><small>consecutive study days</small></div></section>
 <section className="grid"><div className="card wide"><div className="section-head"><div><h2>30-day activity</h2><p className="muted">Daily study effort. Hover-free, simple at-a-glance history.</p></div><strong>{hours(activity.reduce((a,b)=>a+b.minutes,0))}</strong></div><div className="activity-chart">{activity.map(x=><div className="activity-col" key={x.date} title={`${x.date}: ${hours(x.minutes)}`}><i style={{height:`${Math.max(4,x.minutes/maxActivity*100)}%`}}/><small>{new Date(`${x.date}T00:00:00`).getDate()}</small></div>)}</div></div>
 <div className="card"><h2>Best learning day</h2>{best?<><strong className="big-number">{hours(Number(best.minutes))}</strong><p className="muted">{fmtDate(best.session_date)}</p></>:<p className="muted">Log your first session to see it.</p>}<h2 className="subhead">Weekly target</h2><div className="big-progress"><i style={{width:`${Math.min(100,week/data.weeklyTargetMinutes*100)}%`}}/></div><p className="muted">{Math.min(100,Math.round(week/data.weeklyTargetMinutes*100))}% of 10h target</p></div></section>
 <section className="card"><div className="section-head"><div><h2>Skill effort</h2><p className="muted">Click any skill for its detailed learning history.</p></div></div><div className="skill-table">{stats.map(s=><a className="skill-row" href={`/skills/${encodeURIComponent(s.skill)}`} key={s.skill}><div><b>{s.skill}</b><small>{s.sessions} sessions · last studied {fmtDate(s.last_studied)}</small></div><strong>{hours(Number(s.minutes))}</strong></a>)}{stats.length===0&&<p className="muted">No sessions yet.</p>}</div></section>
 <section className="card"><div className="section-head"><div><h2>Skill growth</h2><p className="muted">Weekly effort by skill over the latest tracked weeks.</p></div></div><div className="growth-list">{growth.length?growth.map(([weekKey,vals])=><div className="growth-week" key={weekKey}><b>{fmtDate(weekKey)}</b><div>{[...vals.entries()].map(([skill,min])=><span key={skill} style={{width:`${Math.max(4,Math.min(100,min/600*100))}%`}}><em>{skill}</em><small>{hours(min)}</small></span>)}</div></div>):<p className="muted">Growth appears after you log sessions.</p>}</div></section>
 <section className="card"><div className="section-head"><div><h2>Goals</h2><p className="muted">Set a concrete outcome, deadline and weekly commitment for your custom skills.</p></div><strong>{goals.length} active</strong></div><div className="goal-form"><select value={goalSkill} onChange={e=>setGoalSkill(e.target.value)}>{skills.map(s=><option key={s}>{s}</option>)}</select><input value={outcome} onChange={e=>setOutcome(e.target.value)} placeholder="Target outcome · e.g. Build production-ready SAP CPI integration"/><input type="date" value={deadline} onChange={e=>setDeadline(e.target.value)}/><input type="number" min="0" max="10080" value={weekly} onChange={e=>setWeekly(Number(e.target.value))}/><button onClick={addGoal} disabled={savingGoal||!outcome.trim()}>{savingGoal?'Saving…':'＋ Add goal'}</button></div><div className="goal-list">{goals.map(g=>{const actual=Number(stats.find(s=>s.skill===g.skill_name)?.minutes||0);const currentWeek=Number(weekStats.find(s=>s.skill===g.skill_name)?.minutes||0);const progress=g.weekly_minutes?Math.min(100,Math.round(currentWeek/g.weekly_minutes*100)):0;return <div className="goal" key={g.id}><div className="goal-head"><div><b>{g.skill_name}</b><span>{g.target_outcome}</span></div><button className="remove-skill" onClick={()=>deleteGoal(g.id)}>Delete</button></div><div className="goal-meta"><span>Week: {hours(currentWeek)} / {hours(g.weekly_minutes)}</span><span>{g.deadline?`Due ${fmtDate(g.deadline)}`:'No deadline'}</span><span>{hours(actual)} total skill effort</span></div><div className="bar"><i style={{width:`${progress}%`}}/></div></div>})}</div></section>
 <section className="card"><div className="section-head"><div><h2>Learning journal</h2><p className="muted">Capture what you learned, built, struggled with and need to revisit.</p></div></div><div className="journal-form"><select value={jSkill} onChange={e=>setJSkill(e.target.value)}>{skills.map(s=><option key={s}>{s}</option>)}</select><textarea value={jLearned} onChange={e=>setJLearned(e.target.value)} placeholder="What did I learn?"/><textarea value={jBuilt} onChange={e=>setJBuilt(e.target.value)} placeholder="What did I build?"/><textarea value={jHard} onChange={e=>setJHard(e.target.value)} placeholder="What was difficult?"/><textarea value={jRevisit} onChange={e=>setJRevisit(e.target.value)} placeholder="What should I revisit?"/><textarea value={jResources} onChange={e=>setJResources(e.target.value)} placeholder="Links / resources (optional)"/><button onClick={addJournal} disabled={savingJournal}>{savingJournal?'Saving…':'Save journal entry'}</button></div><div className="journal-list">{journal.map(j=><article className="journal-entry" key={j.id}><div className="section-head"><b>{j.skill_name}</b><small>{fmtDate(j.journal_date)}</small></div>{j.learned&&<p><strong>Learned:</strong> {j.learned}</p>}{j.built&&<p><strong>Built:</strong> {j.built}</p>}{j.difficult&&<p><strong>Difficult:</strong> {j.difficult}</p>}{j.revisit&&<p><strong>Revisit:</strong> {j.revisit}</p>}{j.resources&&<p><strong>Resources:</strong> {j.resources}</p>}</article>)}{journal.length===0&&<p className="muted">Your journal will appear here.</p>}</div></section>
 <footer>Phase 1 · Learning HQ · effort is measured from logged study sessions</footer>
 </main>;
}
