'use client';
import {useEffect,useState} from 'react';
const CORE=['DSA','Java','JVM Performance','System Design','Distributed Systems','AI Engineering','Recognition'];
const fmt=(v?:string)=>v?new Date(`${v}T00:00:00`).toLocaleDateString(undefined,{day:'2-digit',month:'short',year:'numeric'}):'—';
export default function Phase3(){
 const[skills,setSkills]=useState(CORE),[evidence,setEvidence]=useState<any[]>([]),[next,setNext]=useState<any>(null),[q,setQ]=useState(''),[results,setResults]=useState<any[]>([]),[error,setError]=useState(false);
 const[skill,setSkill]=useState('DSA'),[title,setTitle]=useState(''),[type,setType]=useState('PROJECT'),[desc,setDesc]=useState(''),[url,setUrl]=useState(''),[saving,setSaving]=useState(false);
 const load=async()=>{try{const [e,s]=await Promise.all([fetch('/api/phase3/evidence',{cache:'no-store'}),fetch('/api/skills',{cache:'no-store'})]);if(!e.ok||!s.ok)throw new Error();setEvidence(await e.json());const c=await s.json();setSkills([...CORE,...c.map((x:any)=>x.name)]);const n=await fetch('/api/phase3/next',{cache:'no-store'});if(n.ok)setNext(await n.json());}catch{setError(true)}};useEffect(()=>{load()},[]);
 const add=async()=>{if(!title.trim())return;setSaving(true);try{const r=await fetch('/api/phase3/evidence',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({skillName:skill,title,evidenceType:type,description:desc,url})});if(!r.ok)throw new Error();setTitle('');setDesc('');setUrl('');setEvidence(await(await fetch('/api/phase3/evidence')).json());}catch{setError(true)}finally{setSaving(false)}};
 const verify=async(x:any)=>{const r=await fetch(`/api/phase3/evidence/${x.id}`,{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({verified:!x.verified})});if(r.ok)setEvidence(await(await fetch('/api/phase3/evidence')).json());else setError(true)};
 const remove=async(id:number)=>{if(!confirm('Delete this evidence?'))return;const r=await fetch(`/api/phase3/evidence/${id}`,{method:'DELETE'});if(r.ok)setEvidence(x=>x.filter(v=>v.id!==id));else setError(true)};
 const search=async(v:string)=>{setQ(v);if(!v.trim()){setResults([]);return}try{const r=await fetch(`/api/phase3/search?q=${encodeURIComponent(v)}`);if(!r.ok)throw new Error();setResults((await r.json()).results)}catch{setError(true)}};
 return <main><header className="topbar"><div><div className="eyebrow">PHASE 3 · CAREER INTELLIGENCE</div><h1>Portfolio & Career HQ</h1><p>Turn six months of learning into visible evidence and better next actions.</p></div><a className="back-link" href="/phase2">← Execution Hub</a></header>{error&&<div className="notice">Some Phase 3 data could not be loaded or saved.</div>}
 <section className="dsa-stats"><div className="metric"><span>Evidence</span><strong>{evidence.length}</strong><small>{evidence.filter(x=>x.verified).length} verified</small></div><div className="metric"><span>Searchable history</span><strong>∞</strong><small>sessions · journals · projects</small></div><div className="metric"><span>Reviews due</span><strong>{next?.reviewsDue??'—'}</strong><small>retention first</small></div><div className="metric"><span>Active projects</span><strong>{next?.activeProjects??'—'}</strong><small>build evidence</small></div></section>
 <section className="card"><div className="section-head"><div><h2>What should I do next?</h2><p className="muted">Adaptive recommendation from your logged effort and open work.</p></div><strong>AI-style decision engine</strong></div>{next?<div className="next-action"><div><span className="eyebrow">RECOMMENDED SKILL</span><h2>{next.skill}</h2><p>{next.reason}</p></div><div className="next-number">{next.suggestedMinutes} min</div><p className="next-rule">{next.action}</p></div>:<p className="muted">Log more learning activity to generate a recommendation.</p>}</section>
 <section className="card"><div className="section-head"><div><h2>Global search</h2><p className="muted">Search your entire learning history without remembering where you logged it.</p></div></div><input className="global-search" value={q} onChange={e=>search(e.target.value)} placeholder="Search SAP CPI, Kafka, JVM, project names, journal notes…"/>{q&&<div className="search-results">{results.map((r,i)=><div className="search-result" key={`${r.kind}-${r.id}-${i}`}><span>{r.kind}</span><div><b>{r.skill}</b><p>{r.title||'No title'}</p></div><small>{fmt(r.date)}</small></div>)}{results.length===0&&<p className="empty-state">No matches.</p>}</div>}</section>
 <section className="card"><div className="section-head"><div><h2>Portfolio evidence</h2><p className="muted">Create proof for every serious skill: project, article, PR, architecture, certification or measurable result.</p></div><strong>{evidence.filter(x=>x.verified).length}/{evidence.length} verified</strong></div><div className="goal-form"><select value={skill} onChange={e=>setSkill(e.target.value)}>{skills.map(s=><option key={s}>{s}</option>)}</select><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Evidence title · e.g. SAP CPI invoice integration"/><select value={type} onChange={e=>setType(e.target.value)}><option>PROJECT</option><option>ARTICLE</option><option>OPEN_SOURCE</option><option>ARCHITECTURE</option><option>CERTIFICATION</option><option>METRIC</option><option>DEMO</option></select><input value={url} onChange={e=>setUrl(e.target.value)} placeholder="URL (optional)"/><button onClick={add} disabled={saving||!title.trim()}>{saving?'Saving…':'＋ Add evidence'}</button></div><textarea className="evidence-description" value={desc} onChange={e=>setDesc(e.target.value)} placeholder="What proves the skill? Mention scope, your contribution, result and measurable impact."/><div className="evidence-list">{evidence.map(x=><article className="evidence" key={x.id}><div className="goal-head"><div><b>{x.title}</b><span>{x.skill_name} · {x.evidence_type}</span></div><button className="remove-skill" onClick={()=>remove(x.id)}>Delete</button></div>{x.description&&<p>{x.description}</p>}<div className="goal-meta">{x.url&&<a href={x.url} target="_blank" rel="noreferrer">Open evidence ↗</a>}<button onClick={()=>verify(x)}>{x.verified?'✓ Verified':'Mark verified'}</button></div></article>)}{evidence.length===0&&<p className="empty-state">No evidence yet. Start with your strongest project.</p>}</div></section>
 <section className="card"><div className="section-head"><div><h2>Evidence coverage</h2><p className="muted">Skills without proof are your biggest portfolio gaps.</p></div></div>{skills.map(s=>{const rows=evidence.filter(x=>x.skill_name===s);const verified=rows.filter(x=>x.verified).length;return <div className="skill-row" key={s}><div><b>{s}</b><small>{rows.length} evidence items · {verified} verified</small></div><strong>{verified>0?'READY':'GAP'}</strong></div>})}</section>
 <footer>Phase 3 · Learn → Build → Prove → Search → Decide</footer></main>;
}
