-- Simple H2 schema for the FAANG Engineering Tracker
-- H2-compatible SQL

CREATE TABLE IF NOT EXISTS task_completion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(100) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_at TIMESTAMP,
    UNIQUE(task_id)
);

CREATE TABLE IF NOT EXISTS study_session (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_date DATE NOT NULL,
    track VARCHAR(50) NOT NULL,
    minutes INT NOT NULL,
    notes VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS application (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company VARCHAR(150) NOT NULL,
    role VARCHAR(200) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'PLANNED',
    applied_date DATE,
    notes VARCHAR(2000)
);

CREATE TABLE IF NOT EXISTS recognition_activity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    activity_date DATE NOT NULL,
    activity_type VARCHAR(50) NOT NULL,
    title VARCHAR(250) NOT NULL,
    url VARCHAR(1000),
    notes VARCHAR(2000)
);
