INSERT INTO dsa_problem (id, title, url, difficulty, pattern) VALUES
('two-sum','Two Sum','https://leetcode.com/problems/two-sum/','EASY','Hash Map'),
('valid-anagram','Valid Anagram','https://leetcode.com/problems/valid-anagram/','EASY','Hash Map'),
('group-anagrams','Group Anagrams','https://leetcode.com/problems/group-anagrams/','MEDIUM','Hash Map'),
('top-k-frequent-elements','Top K Frequent Elements','https://leetcode.com/problems/top-k-frequent-elements/','MEDIUM','Heap'),
('product-except-self','Product of Array Except Self','https://leetcode.com/problems/product-of-array-except-self/','MEDIUM','Prefix Sum'),
('longest-consecutive-sequence','Longest Consecutive Sequence','https://leetcode.com/problems/longest-consecutive-sequence/','MEDIUM','Hash Set'),
('valid-palindrome','Valid Palindrome','https://leetcode.com/problems/valid-palindrome/','EASY','Two Pointers'),
('three-sum','3Sum','https://leetcode.com/problems/3sum/','MEDIUM','Two Pointers'),
('container-most-water','Container With Most Water','https://leetcode.com/problems/container-with-most-water/','MEDIUM','Two Pointers'),
('longest-substring','Longest Substring Without Repeating Characters','https://leetcode.com/problems/longest-substring-without-repeating-characters/','MEDIUM','Sliding Window'),
('minimum-window-substring','Minimum Window Substring','https://leetcode.com/problems/minimum-window-substring/','HARD','Sliding Window'),
('valid-parentheses','Valid Parentheses','https://leetcode.com/problems/valid-parentheses/','EASY','Stack'),
('daily-temperatures','Daily Temperatures','https://leetcode.com/problems/daily-temperatures/','MEDIUM','Monotonic Stack'),
('binary-search','Binary Search','https://leetcode.com/problems/binary-search/','EASY','Binary Search'),
('search-rotated-array','Search in Rotated Sorted Array','https://leetcode.com/problems/search-in-rotated-sorted-array/','MEDIUM','Binary Search'),
('reverse-linked-list','Reverse Linked List','https://leetcode.com/problems/reverse-linked-list/','EASY','Linked List'),
('merge-two-lists','Merge Two Sorted Lists','https://leetcode.com/problems/merge-two-sorted-lists/','EASY','Linked List'),
('lru-cache','LRU Cache','https://leetcode.com/problems/lru-cache/','MEDIUM','Design + Linked List'),
('invert-tree','Invert Binary Tree','https://leetcode.com/problems/invert-binary-tree/','EASY','Trees DFS'),
('max-depth-tree','Maximum Depth of Binary Tree','https://leetcode.com/problems/maximum-depth-of-binary-tree/','EASY','Trees DFS'),
('validate-bst','Validate Binary Search Tree','https://leetcode.com/problems/validate-binary-search-tree/','MEDIUM','BST'),
('level-order','Binary Tree Level Order Traversal','https://leetcode.com/problems/binary-tree-level-order-traversal/','MEDIUM','Trees BFS'),
('lowest-common-ancestor','Lowest Common Ancestor of a Binary Tree','https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/','MEDIUM','Trees DFS'),
('kth-smallest-bst','Kth Smallest Element in a BST','https://leetcode.com/problems/kth-smallest-element-in-a-bst/','MEDIUM','BST'),
('kth-largest-stream','Kth Largest Element in a Stream','https://leetcode.com/problems/kth-largest-element-in-a-stream/','EASY','Heap'),
('k-closest-points','K Closest Points to Origin','https://leetcode.com/problems/k-closest-points-to-origin/','MEDIUM','Heap'),
('number-islands','Number of Islands','https://leetcode.com/problems/number-of-islands/','MEDIUM','Graphs DFS/BFS'),
('clone-graph','Clone Graph','https://leetcode.com/problems/clone-graph/','MEDIUM','Graphs BFS/DFS'),
('course-schedule','Course Schedule','https://leetcode.com/problems/course-schedule/','MEDIUM','Topological Sort'),
('rotting-oranges','Rotting Oranges','https://leetcode.com/problems/rotting-oranges/','MEDIUM','Graphs BFS'),
('subsets','Subsets','https://leetcode.com/problems/subsets/','MEDIUM','Backtracking'),
('combination-sum','Combination Sum','https://leetcode.com/problems/combination-sum/','MEDIUM','Backtracking'),
('word-search','Word Search','https://leetcode.com/problems/word-search/','MEDIUM','Backtracking'),
('climbing-stairs','Climbing Stairs','https://leetcode.com/problems/climbing-stairs/','EASY','1D DP'),
('house-robber','House Robber','https://leetcode.com/problems/house-robber/','MEDIUM','1D DP'),
('coin-change','Coin Change','https://leetcode.com/problems/coin-change/','MEDIUM','1D DP'),
('longest-increasing-subsequence','Longest Increasing Subsequence','https://leetcode.com/problems/longest-increasing-subsequence/','MEDIUM','1D DP'),
('unique-paths','Unique Paths','https://leetcode.com/problems/unique-paths/','MEDIUM','2D DP'),
('word-break','Word Break','https://leetcode.com/problems/word-break/','MEDIUM','DP + Hash Set'),
('jump-game','Jump Game','https://leetcode.com/problems/jump-game/','MEDIUM','Greedy'),
('merge-intervals','Merge Intervals','https://leetcode.com/problems/merge-intervals/','MEDIUM','Intervals'),
('insert-interval','Insert Interval','https://leetcode.com/problems/insert-interval/','MEDIUM','Intervals'),
('non-overlap-intervals','Non-overlapping Intervals','https://leetcode.com/problems/non-overlapping-intervals/','MEDIUM','Intervals Greedy'),
('trie-prefix-tree','Implement Trie (Prefix Tree)','https://leetcode.com/problems/implement-trie-prefix-tree/','MEDIUM','Trie'),
('word-dictionary','Design Add and Search Words Data Structure','https://leetcode.com/problems/design-add-and-search-words-data-structure/','MEDIUM','Trie'),
('union-find','Number of Connected Components in an Undirected Graph','https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/','MEDIUM','Union Find'),
('network-delay','Network Delay Time','https://leetcode.com/problems/network-delay-time/','MEDIUM','Dijkstra'),
('cheapest-flights','Cheapest Flights Within K Stops','https://leetcode.com/problems/cheapest-flights-within-k-stops/','MEDIUM','Shortest Path'),
('single-number','Single Number','https://leetcode.com/problems/single-number/','EASY','Bit Manipulation'),
('counting-bits','Counting Bits','https://leetcode.com/problems/counting-bits/','EASY','Bit Manipulation');
