INSERT INTO dsa_problem (id, title, url, difficulty, pattern) VALUES
('two-sum','Two Sum','https://leetcode.com/problems/two-sum/','Easy','Hash Map'),
('valid-anagram','Valid Anagram','https://leetcode.com/problems/valid-anagram/','Easy','Hash Map'),
('group-anagrams','Group Anagrams','https://leetcode.com/problems/group-anagrams/','Medium','Hash Map'),
('longest-substring','Longest Substring Without Repeating Characters','https://leetcode.com/problems/longest-substring-without-repeating-characters/','Medium','Sliding Window'),
('best-time-stock','Best Time to Buy and Sell Stock','https://leetcode.com/problems/best-time-to-buy-and-sell-stock/','Easy','Two Pointers'),
('valid-parentheses','Valid Parentheses','https://leetcode.com/problems/valid-parentheses/','Easy','Stack'),
('binary-search','Binary Search','https://leetcode.com/problems/binary-search/','Easy','Binary Search'),
('reverse-linked-list','Reverse Linked List','https://leetcode.com/problems/reverse-linked-list/','Easy','Linked List'),
('maximum-depth-tree','Maximum Depth of Binary Tree','https://leetcode.com/problems/maximum-depth-of-binary-tree/','Easy','Trees'),
('number-of-islands','Number of Islands','https://leetcode.com/problems/number-of-islands/','Medium','Graphs'),
('climbing-stairs','Climbing Stairs','https://leetcode.com/problems/climbing-stairs/','Easy','Dynamic Programming'),
('coin-change','Coin Change','https://leetcode.com/problems/coin-change/','Medium','Dynamic Programming'),
('contains-duplicate','Contains Duplicate','https://leetcode.com/problems/contains-duplicate/','Easy','Hash Map'),
('product-except-self','Product of Array Except Self','https://leetcode.com/problems/product-of-array-except-self/','Medium','Arrays'),
('maximum-subarray','Maximum Subarray','https://leetcode.com/problems/maximum-subarray/','Medium','Arrays'),
('three-sum','3Sum','https://leetcode.com/problems/3sum/','Medium','Two Pointers'),
('container-most-water','Container With Most Water','https://leetcode.com/problems/container-with-most-water/','Medium','Two Pointers'),
('longest-repeating-character','Longest Repeating Character Replacement','https://leetcode.com/problems/longest-repeating-character-replacement/','Medium','Sliding Window'),
('permutation-in-string','Permutation in String','https://leetcode.com/problems/permutation-in-string/','Medium','Sliding Window'),
('min-window-substring','Minimum Window Substring','https://leetcode.com/problems/minimum-window-substring/','Hard','Sliding Window'),
('daily-temperatures','Daily Temperatures','https://leetcode.com/problems/daily-temperatures/','Medium','Monotonic Stack'),
('min-stack','Min Stack','https://leetcode.com/problems/min-stack/','Medium','Stack'),
('evaluate-rpn','Evaluate Reverse Polish Notation','https://leetcode.com/problems/evaluate-reverse-polish-notation/','Medium','Stack'),
('car-fleet','Car Fleet','https://leetcode.com/problems/car-fleet/','Medium','Monotonic Stack'),
('search-rotated-array','Search in Rotated Sorted Array','https://leetcode.com/problems/search-in-rotated-sorted-array/','Medium','Binary Search'),
('koko-eating-bananas','Koko Eating Bananas','https://leetcode.com/problems/koko-eating-bananas/','Medium','Binary Search'),
('find-min-rotated','Find Minimum in Rotated Sorted Array','https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/','Medium','Binary Search'),
('merge-two-lists','Merge Two Sorted Lists','https://leetcode.com/problems/merge-two-sorted-lists/','Easy','Linked List'),
('reorder-list','Reorder List','https://leetcode.com/problems/reorder-list/','Medium','Linked List'),
('remove-nth-node','Remove Nth Node From End of List','https://leetcode.com/problems/remove-nth-node-from-end-of-list/','Medium','Linked List'),
('linked-list-cycle','Linked List Cycle','https://leetcode.com/problems/linked-list-cycle/','Easy','Linked List'),
('invert-tree','Invert Binary Tree','https://leetcode.com/problems/invert-binary-tree/','Easy','Trees'),
('same-tree','Same Tree','https://leetcode.com/problems/same-tree/','Easy','Trees'),
('subtree-another-tree','Subtree of Another Tree','https://leetcode.com/problems/subtree-of-another-tree/','Easy','Trees'),
('lowest-common-ancestor-bst','Lowest Common Ancestor of a Binary Search Tree','https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/','Medium','Trees'),
('binary-tree-level-order','Binary Tree Level Order Traversal','https://leetcode.com/problems/binary-tree-level-order-traversal/','Medium','Trees'),
('validate-bst','Validate Binary Search Tree','https://leetcode.com/problems/validate-binary-search-tree/','Medium','Trees'),
('kth-smallest-bst','Kth Smallest Element in a BST','https://leetcode.com/problems/kth-smallest-element-in-a-bst/','Medium','Trees'),
('clone-graph','Clone Graph','https://leetcode.com/problems/clone-graph/','Medium','Graphs'),
('course-schedule','Course Schedule','https://leetcode.com/problems/course-schedule/','Medium','Graphs'),
('pacific-atlantic','Pacific Atlantic Water Flow','https://leetcode.com/problems/pacific-atlantic-water-flow/','Medium','Graphs'),
('rotting-oranges','Rotting Oranges','https://leetcode.com/problems/rotting-oranges/','Medium','Graphs'),
('word-ladder','Word Ladder','https://leetcode.com/problems/word-ladder/','Hard','Graphs'),
('house-robber','House Robber','https://leetcode.com/problems/house-robber/','Medium','Dynamic Programming'),
('house-robber-ii','House Robber II','https://leetcode.com/problems/house-robber-ii/','Medium','Dynamic Programming'),
('longest-palindromic-substring','Longest Palindromic Substring','https://leetcode.com/problems/longest-palindromic-substring/','Medium','Dynamic Programming'),
('decode-ways','Decode Ways','https://leetcode.com/problems/decode-ways/','Medium','Dynamic Programming'),
('unique-paths','Unique Paths','https://leetcode.com/problems/unique-paths/','Medium','Dynamic Programming'),
('word-break','Word Break','https://leetcode.com/problems/word-break/','Medium','Dynamic Programming'),
('partition-equal-subset','Partition Equal Subset Sum','https://leetcode.com/problems/partition-equal-subset-sum/','Medium','Dynamic Programming'),
('maximum-product-subarray','Maximum Product Subarray','https://leetcode.com/problems/maximum-product-subarray/','Medium','Dynamic Programming'),
('subsets','Subsets','https://leetcode.com/problems/subsets/','Medium','Backtracking'),
('combination-sum','Combination Sum','https://leetcode.com/problems/combination-sum/','Medium','Backtracking'),
('permutations','Permutations','https://leetcode.com/problems/permutations/','Medium','Backtracking'),
('word-search','Word Search','https://leetcode.com/problems/word-search/','Medium','Backtracking'),
('letter-combinations-phone','Letter Combinations of a Phone Number','https://leetcode.com/problems/letter-combinations-of-a-phone-number/','Medium','Backtracking'),
('kth-largest-element','Kth Largest Element in an Array','https://leetcode.com/problems/kth-largest-element-in-an-array/','Medium','Heap'),
('top-k-frequent','Top K Frequent Elements','https://leetcode.com/problems/top-k-frequent-elements/','Medium','Heap'),
('merge-k-sorted-lists','Merge k Sorted Lists','https://leetcode.com/problems/merge-k-sorted-lists/','Hard','Heap'),
('task-scheduler','Task Scheduler','https://leetcode.com/problems/task-scheduler/','Medium','Heap'),
('meeting-rooms-ii','Meeting Rooms II','https://leetcode.com/problems/meeting-rooms-ii/','Medium','Heap')
ON CONFLICT (id) DO UPDATE SET
  title = EXCLUDED.title,
  url = EXCLUDED.url,
  difficulty = EXCLUDED.difficulty,
  pattern = EXCLUDED.pattern;
