INSERT INTO dsa_problem (id,title,url,difficulty,pattern) VALUES
('valid-palindrome','Valid Palindrome','https://leetcode.com/problems/valid-palindrome/','Easy','Two Pointers'),
('two-sum-ii','Two Sum II - Input Array Is Sorted','https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/','Medium','Two Pointers'),
('valid-sudoku','Valid Sudoku','https://leetcode.com/problems/valid-sudoku/','Medium','Arrays'),
('encode-decode-strings','Encode and Decode Strings','https://leetcode.com/problems/encode-and-decode-strings/','Medium','Arrays'),
('longest-consecutive-sequence','Longest Consecutive Sequence','https://leetcode.com/problems/longest-consecutive-sequence/','Medium','Hash Map'),
('majority-element','Majority Element','https://leetcode.com/problems/majority-element/','Easy','Arrays'),
('sort-colors','Sort Colors','https://leetcode.com/problems/sort-colors/','Medium','Two Pointers'),
('trapping-rain-water','Trapping Rain Water','https://leetcode.com/problems/trapping-rain-water/','Hard','Two Pointers'),
('valid-palindrome-ii','Valid Palindrome II','https://leetcode.com/problems/valid-palindrome-ii/','Easy','Two Pointers'),
('move-zeroes','Move Zeroes','https://leetcode.com/problems/move-zeroes/','Easy','Two Pointers'),
('merge-sorted-array','Merge Sorted Array','https://leetcode.com/problems/merge-sorted-array/','Easy','Arrays'),
('rotate-array','Rotate Array','https://leetcode.com/problems/rotate-array/','Medium','Arrays'),
('best-time-stock-ii','Best Time to Buy and Sell Stock II','https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/','Medium','Greedy'),
('jump-game','Jump Game','https://leetcode.com/problems/jump-game/','Medium','Greedy'),
('jump-game-ii','Jump Game II','https://leetcode.com/problems/jump-game-ii/','Medium','Greedy'),
('gas-station','Gas Station','https://leetcode.com/problems/gas-station/','Medium','Greedy'),
('candy','Candy','https://leetcode.com/problems/candy/','Hard','Greedy'),
('maximum-number-of-k-sum-pairs','Max Number of K-Sum Pairs','https://leetcode.com/problems/max-number-of-k-sum-pairs/','Medium','Two Pointers'),
('longest-substring-at-most-k','Longest Substring with At Most K Distinct Characters','https://leetcode.com/problems/longest-substring-with-at-most-k-distinct-characters/','Medium','Sliding Window'),
('fruit-into-baskets','Fruit Into Baskets','https://leetcode.com/problems/fruit-into-baskets/','Medium','Sliding Window'),
('sliding-window-maximum','Sliding Window Maximum','https://leetcode.com/problems/sliding-window-maximum/','Hard','Sliding Window'),
('find-all-anagrams','Find All Anagrams in a String','https://leetcode.com/problems/find-all-anagrams-in-a-string/','Medium','Sliding Window'),
('minimum-size-subarray-sum','Minimum Size Subarray Sum','https://leetcode.com/problems/minimum-size-subarray-sum/','Medium','Sliding Window'),
('valid-parentheses-ii','Remove Invalid Parentheses','https://leetcode.com/problems/remove-invalid-parentheses/','Hard','Stack'),
('generate-parentheses','Generate Parentheses','https://leetcode.com/problems/generate-parentheses/','Medium','Backtracking'),
('largest-rectangle-histogram','Largest Rectangle in Histogram','https://leetcode.com/problems/largest-rectangle-in-histogram/','Hard','Monotonic Stack'),
('next-greater-element-i','Next Greater Element I','https://leetcode.com/problems/next-greater-element-i/','Easy','Monotonic Stack'),
('next-greater-element-ii','Next Greater Element II','https://leetcode.com/problems/next-greater-element-ii/','Medium','Monotonic Stack'),
('asteroid-collision','Asteroid Collision','https://leetcode.com/problems/asteroid-collision/','Medium','Stack'),
('simplify-path','Simplify Path','https://leetcode.com/problems/simplify-path/','Medium','Stack'),
('car-fleet-ii','Car Fleet II','https://leetcode.com/problems/car-fleet-ii/','Hard','Monotonic Stack'),
('search-insert-position','Search Insert Position','https://leetcode.com/problems/search-insert-position/','Easy','Binary Search'),
('first-bad-version','First Bad Version','https://leetcode.com/problems/first-bad-version/','Easy','Binary Search'),
('find-peak-element','Find Peak Element','https://leetcode.com/problems/find-peak-element/','Medium','Binary Search'),
('time-based-key-value-store','Time Based Key-Value Store','https://leetcode.com/problems/time-based-key-value-store/','Medium','Binary Search'),
('median-two-sorted-arrays','Median of Two Sorted Arrays','https://leetcode.com/problems/median-of-two-sorted-arrays/','Hard','Binary Search'),
('successful-pairs','Successful Pairs of Spells and Potions','https://leetcode.com/problems/successful-pairs-of-spells-and-potions/','Medium','Binary Search'),
('find-first-last-position','Find First and Last Position of Element in Sorted Array','https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/','Medium','Binary Search'),
('reverse-linked-list-ii','Reverse Linked List II','https://leetcode.com/problems/reverse-linked-list-ii/','Medium','Linked List'),
('add-two-numbers','Add Two Numbers','https://leetcode.com/problems/add-two-numbers/','Medium','Linked List'),
('copy-list-random-pointer','Copy List with Random Pointer','https://leetcode.com/problems/copy-list-with-random-pointer/','Medium','Linked List'),
('find-duplicate-number','Find the Duplicate Number','https://leetcode.com/problems/find-the-duplicate-number/','Medium','Linked List'),
('lru-cache','LRU Cache','https://leetcode.com/problems/lru-cache/','Medium','Linked List'),
('merge-in-between-linked-lists','Merge In Between Linked Lists','https://leetcode.com/problems/merge-in-between-linked-lists/','Medium','Linked List'),
('palindrome-linked-list','Palindrome Linked List','https://leetcode.com/problems/palindrome-linked-list/','Easy','Linked List'),
('intersection-two-linked-lists','Intersection of Two Linked Lists','https://leetcode.com/problems/intersection-of-two-linked-lists/','Easy','Linked List'),
('sort-list','Sort List','https://leetcode.com/problems/sort-list/','Medium','Linked List'),
('reverse-nodes-k-group','Reverse Nodes in k-Group','https://leetcode.com/problems/reverse-nodes-in-k-group/','Hard','Linked List'),
('rotate-list','Rotate List','https://leetcode.com/problems/rotate-list/','Medium','Linked List'),
('middle-linked-list','Middle of the Linked List','https://leetcode.com/problems/middle-of-the-linked-list/','Easy','Linked List'),
('delete-node-linked-list','Delete Node in a Linked List','https://leetcode.com/problems/delete-node-in-a-linked-list/','Medium','Linked List'),
('balanced-binary-tree','Balanced Binary Tree','https://leetcode.com/problems/balanced-binary-tree/','Easy','Trees'),
('diameter-binary-tree','Diameter of Binary Tree','https://leetcode.com/problems/diameter-of-binary-tree/','Easy','Trees'),
('binary-tree-right-side-view','Binary Tree Right Side View','https://leetcode.com/problems/binary-tree-right-side-view/','Medium','Trees'),
('count-good-nodes','Count Good Nodes in Binary Tree','https://leetcode.com/problems/count-good-nodes-in-binary-tree/','Medium','Trees'),
('construct-tree-pre-in','Construct Binary Tree from Preorder and Inorder Traversal','https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/','Medium','Trees'),
('serialize-deserialize-tree','Serialize and Deserialize Binary Tree','https://leetcode.com/problems/serialize-and-deserialize-binary-tree/','Hard','Trees'),
('binary-tree-max-path-sum','Binary Tree Maximum Path Sum','https://leetcode.com/problems/binary-tree-maximum-path-sum/','Hard','Trees'),
('path-sum','Path Sum','https://leetcode.com/problems/path-sum/','Easy','Trees'),
('path-sum-ii','Path Sum II','https://leetcode.com/problems/path-sum-ii/','Medium','Trees'),
('sum-root-leaf-numbers','Sum Root to Leaf Numbers','https://leetcode.com/problems/sum-root-to-leaf-numbers/','Medium','Trees'),
('populating-next-right-pointers','Populating Next Right Pointers in Each Node','https://leetcode.com/problems/populating-next-right-pointers-in-each-node/','Medium','Trees'),
('binary-tree-zigzag','Binary Tree Zigzag Level Order Traversal','https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/','Medium','Trees'),
('binary-tree-inorder','Binary Tree Inorder Traversal','https://leetcode.com/problems/binary-tree-inorder-traversal/','Easy','Trees'),
('binary-tree-preorder','Binary Tree Preorder Traversal','https://leetcode.com/problems/binary-tree-preorder-traversal/','Easy','Trees'),
('binary-tree-postorder','Binary Tree Postorder Traversal','https://leetcode.com/problems/binary-tree-postorder-traversal/','Easy','Trees'),
('implement-trie','Implement Trie (Prefix Tree)','https://leetcode.com/problems/implement-trie-prefix-tree/','Medium','Trie'),
('design-add-search-words','Design Add and Search Words Data Structure','https://leetcode.com/problems/design-add-and-search-words-data-structure/','Medium','Trie'),
('word-search-ii','Word Search II','https://leetcode.com/problems/word-search-ii/','Hard','Trie'),
('replace-words','Replace Words','https://leetcode.com/problems/replace-words/','Medium','Trie'),
('longest-word-dictionary','Longest Word in Dictionary','https://leetcode.com/problems/longest-word-in-dictionary/','Medium','Trie'),
('max-area-island','Max Area of Island','https://leetcode.com/problems/max-area-of-island/','Medium','Graphs'),
('surrounded-regions','Surrounded Regions','https://leetcode.com/problems/surrounded-regions/','Medium','Graphs'),
('graph-valid-tree','Graph Valid Tree','https://leetcode.com/problems/graph-valid-tree/','Medium','Graphs'),
('number-connected-components','Number of Connected Components in an Undirected Graph','https://leetcode.com/problems/number-of-connected-components-in-an-undirected-graph/','Medium','Graphs'),
('redundant-connection','Redundant Connection','https://leetcode.com/problems/redundant-connection/','Medium','Graphs'),
('network-delay-time','Network Delay Time','https://leetcode.com/problems/network-delay-time/','Medium','Graphs'),
('cheapest-flights-k-stops','Cheapest Flights Within K Stops','https://leetcode.com/problems/cheapest-flights-within-k-stops/','Medium','Graphs'),
('reconstruct-itinerary','Reconstruct Itinerary','https://leetcode.com/problems/reconstruct-itinerary/','Hard','Graphs'),
('min-cost-connect-points','Min Cost to Connect All Points','https://leetcode.com/problems/min-cost-connect-points/','Medium','Graphs'),
('swim-in-rising-water','Swim in Rising Water','https://leetcode.com/problems/swim-in-rising-water/','Hard','Graphs'),
('alien-dictionary','Alien Dictionary','https://leetcode.com/problems/alien-dictionary/','Hard','Graphs'),
('is-graph-bipartite','Is Graph Bipartite?','https://leetcode.com/problems/is-graph-bipartite/','Medium','Graphs'),
('open-lock','Open the Lock','https://leetcode.com/problems/open-the-lock/','Medium','Graphs'),
('walls-and-gates','Walls and Gates','https://leetcode.com/problems/walls-and-gates/','Medium','Graphs'),
('combinations','Combinations','https://leetcode.com/problems/combinations/','Medium','Backtracking'),
('combination-sum-ii','Combination Sum II','https://leetcode.com/problems/combination-sum-ii/','Medium','Backtracking'),
('permutation-sequence','Permutation Sequence','https://leetcode.com/problems/permutation-sequence/','Hard','Backtracking'),
('n-queens','N-Queens','https://leetcode.com/problems/n-queens/','Hard','Backtracking'),
('n-queens-ii','N-Queens II','https://leetcode.com/problems/n-queens-ii/','Hard','Backtracking'),
('palindrome-partitioning','Palindrome Partitioning','https://leetcode.com/problems/palindrome-partitioning/','Medium','Backtracking'),
('restore-ip-addresses','Restore IP Addresses','https://leetcode.com/problems/restore-ip-addresses/','Medium','Backtracking'),
('letter-case-permutation','Letter Case Permutation','https://leetcode.com/problems/letter-case-permutation/','Medium','Backtracking'),
('generate-abbreviations','Generalized Abbreviation','https://leetcode.com/problems/generalized-abbreviation/','Medium','Backtracking'),
('subsets-ii','Subsets II','https://leetcode.com/problems/subsets-ii/','Medium','Backtracking'),
('house-robber-iii','House Robber III','https://leetcode.com/problems/house-robber-iii/','Medium','Dynamic Programming'),
('longest-increasing-subsequence','Longest Increasing Subsequence','https://leetcode.com/problems/longest-increasing-subsequence/','Medium','Dynamic Programming'),
('longest-common-subsequence','Longest Common Subsequence','https://leetcode.com/problems/longest-common-subsequence/','Medium','Dynamic Programming'),
('edit-distance','Edit Distance','https://leetcode.com/problems/edit-distance/','Medium','Dynamic Programming'),
('distinct-subsequences','Distinct Subsequences','https://leetcode.com/problems/distinct-subsequences/','Hard','Dynamic Programming'),
('interleaving-string','Interleaving String','https://leetcode.com/problems/interleaving-string/','Medium','Dynamic Programming'),
('regular-expression-matching','Regular Expression Matching','https://leetcode.com/problems/regular-expression-matching/','Hard','Dynamic Programming'),
('wildcard-matching','Wildcard Matching','https://leetcode.com/problems/wildcard-matching/','Hard','Dynamic Programming'),
('target-sum','Target Sum','https://leetcode.com/problems/target-sum/','Medium','Dynamic Programming'),
('last-stone-weight-ii','Last Stone Weight II','https://leetcode.com/problems/last-stone-weight-ii/','Medium','Dynamic Programming'),
('coin-change-ii','Coin Change II','https://leetcode.com/problems/coin-change-ii/','Medium','Dynamic Programming'),
('combination-sum-iv','Combination Sum IV','https://leetcode.com/problems/combination-sum-iv/','Medium','Dynamic Programming'),
('min-cost-climbing-stairs','Min Cost Climbing Stairs','https://leetcode.com/problems/min-cost-climbing-stairs/','Easy','Dynamic Programming'),
('palindromic-substrings','Palindromic Substrings','https://leetcode.com/problems/palindromic-substrings/','Medium','Dynamic Programming'),
('longest-palindromic-subsequence','Longest Palindromic Subsequence','https://leetcode.com/problems/longest-palindromic-subsequence/','Medium','Dynamic Programming'),
('maximum-profit-job-scheduling','Maximum Profit in Job Scheduling','https://leetcode.com/problems/maximum-profit-in-job-scheduling/','Hard','Dynamic Programming'),
('burst-balloons','Burst Balloons','https://leetcode.com/problems/burst-balloons/','Hard','Dynamic Programming'),
('maximal-square','Maximal Square','https://leetcode.com/problems/maximal-square/','Medium','Dynamic Programming'),
('triangle','Triangle','https://leetcode.com/problems/triangle/','Medium','Dynamic Programming'),
('unique-paths-ii','Unique Paths II','https://leetcode.com/problems/unique-paths-ii/','Medium','Dynamic Programming'),
('minimum-path-sum','Minimum Path Sum','https://leetcode.com/problems/minimum-path-sum/','Medium','Dynamic Programming'),
('word-break-ii','Word Break II','https://leetcode.com/problems/word-break-ii/','Hard','Dynamic Programming'),
('kth-largest-stream','Kth Largest Element in a Stream','https://leetcode.com/problems/kth-largest-element-in-a-stream/','Easy','Heap'),
('last-stone-weight','Last Stone Weight','https://leetcode.com/problems/last-stone-weight/','Easy','Heap'),
('find-median-data-stream','Find Median from Data Stream','https://leetcode.com/problems/find-median-from-data-stream/','Hard','Heap')
ON CONFLICT (id) DO NOTHING;
