INSERT INTO dsa_problem (id,title,url,difficulty,pattern) VALUES
('k-closest-points','K Closest Points to Origin','https://leetcode.com/problems/k-closest-points-to-origin/','Medium','Heap'),
('twitter-design','Design Twitter','https://leetcode.com/problems/design-twitter/','Medium','Heap'),
('reorganize-string','Reorganize String','https://leetcode.com/problems/reorganize-string/','Medium','Heap'),
('ipo','IPO','https://leetcode.com/problems/ipo/','Hard','Heap'),
('smallest-range-k-lists','Smallest Range Covering Elements from K Lists','https://leetcode.com/problems/smallest-range-covering-elements-from-k-lists/','Hard','Heap'),
('meeting-rooms','Meeting Rooms','https://leetcode.com/problems/meeting-rooms/','Easy','Intervals'),
('merge-intervals','Merge Intervals','https://leetcode.com/problems/merge-intervals/','Medium','Intervals'),
('insert-interval','Insert Interval','https://leetcode.com/problems/insert-interval/','Medium','Intervals'),
('non-overlapping-intervals','Non-overlapping Intervals','https://leetcode.com/problems/non-overlapping-intervals/','Medium','Intervals'),
('meeting-rooms-iii','Meeting Rooms III','https://leetcode.com/problems/meeting-rooms-iii/','Hard','Intervals'),
('minimum-interval-query','Minimum Interval to Include Each Query','https://leetcode.com/problems/minimum-interval-to-include-each-query/','Hard','Intervals'),
('partition-labels','Partition Labels','https://leetcode.com/problems/partition-labels/','Medium','Greedy'),
('hand-straights','Hand of Straights','https://leetcode.com/problems/hand-of-straights/','Medium','Greedy'),
('merge-triplets','Merge Triplets to Form Target Triplet','https://leetcode.com/problems/merge-triplets-to-form-target-triplet/','Medium','Greedy'),
('queue-reconstruction-height','Queue Reconstruction by Height','https://leetcode.com/problems/queue-reconstruction-by-height/','Medium','Greedy'),
('jump-game-iii','Jump Game III','https://leetcode.com/problems/jump-game-iii/','Medium','Graphs'),
('assign-cookies','Assign Cookies','https://leetcode.com/problems/assign-cookies/','Easy','Greedy'),
('boats-save-people','Boats to Save People','https://leetcode.com/problems/boats-to-save-people/','Medium','Greedy'),
('partition-array-disjoint','Partition Array into Disjoint Intervals','https://leetcode.com/problems/partition-array-into-disjoint-intervals/','Medium','Greedy'),
('single-number','Single Number','https://leetcode.com/problems/single-number/','Easy','Bit Manipulation'),
('number-1-bits','Number of 1 Bits','https://leetcode.com/problems/number-of-1-bits/','Easy','Bit Manipulation'),
('counting-bits','Counting Bits','https://leetcode.com/problems/counting-bits/','Easy','Bit Manipulation'),
('reverse-bits','Reverse Bits','https://leetcode.com/problems/reverse-bits/','Easy','Bit Manipulation'),
('missing-number','Missing Number','https://leetcode.com/problems/missing-number/','Easy','Bit Manipulation'),
('sum-two-integers','Sum of Two Integers','https://leetcode.com/problems/sum-of-two-integers/','Medium','Bit Manipulation'),
('single-number-ii','Single Number II','https://leetcode.com/problems/single-number-ii/','Medium','Bit Manipulation'),
('power-of-two','Power of Two','https://leetcode.com/problems/power-of-two/','Easy','Bit Manipulation'),
('reverse-integer','Reverse Integer','https://leetcode.com/problems/reverse-integer/','Medium','Math'),
('palindrome-number','Palindrome Number','https://leetcode.com/problems/palindrome-number/','Easy','Math'),
('happy-number','Happy Number','https://leetcode.com/problems/happy-number/','Easy','Math'),
('pow-x-n','Pow(x, n)','https://leetcode.com/problems/powx-n/','Medium','Math'),
('multiply-strings','Multiply Strings','https://leetcode.com/problems/multiply-strings/','Medium','Math'),
('plus-one','Plus One','https://leetcode.com/problems/plus-one/','Easy','Math'),
('rotate-image','Rotate Image','https://leetcode.com/problems/rotate-image/','Medium','Math'),
('spiral-matrix','Spiral Matrix','https://leetcode.com/problems/spiral-matrix/','Medium','Arrays'),
('set-matrix-zeroes','Set Matrix Zeroes','https://leetcode.com/problems/set-matrix-zeroes/','Medium','Arrays'),
('game-of-life','Game of Life','https://leetcode.com/problems/game-of-life/','Medium','Arrays'),
('reshape-matrix','Reshape the Matrix','https://leetcode.com/problems/reshape-the-matrix/','Easy','Arrays'),
('search-2d-matrix','Search a 2D Matrix','https://leetcode.com/problems/search-a-2d-matrix/','Medium','Binary Search'),
('search-2d-matrix-ii','Search a 2D Matrix II','https://leetcode.com/problems/search-a-2d-matrix-ii/','Medium','Binary Search'),
('capacity-ship-packages','Capacity To Ship Packages Within D Days','https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/','Medium','Binary Search'),
('split-array-largest-sum','Split Array Largest Sum','https://leetcode.com/problems/split-array-largest-sum/','Hard','Binary Search'),
('minimum-speed-arrive-time','Minimum Speed to Arrive on Time','https://leetcode.com/problems/minimum-speed-to-arrive-on-time/','Medium','Binary Search'),
('random-pick-weight','Random Pick with Weight','https://leetcode.com/problems/random-pick-with-weight/','Medium','Binary Search'),
('range-sum-query','Range Sum Query - Immutable','https://leetcode.com/problems/range-sum-query-immutable/','Easy','Prefix Sum'),
('subarray-sum-k','Subarray Sum Equals K','https://leetcode.com/problems/subarray-sum-equals-k/','Medium','Prefix Sum'),
('continuous-subarray-sum','Continuous Subarray Sum','https://leetcode.com/problems/continuous-subarray-sum/','Medium','Prefix Sum'),
('range-sum-query-2d','Range Sum Query 2D - Immutable','https://leetcode.com/problems/range-sum-query-2d-immutable/','Medium','Prefix Sum'),
('count-number-nice-subarrays','Count Number of Nice Subarrays','https://leetcode.com/problems/count-number-of-nice-subarrays/','Medium','Prefix Sum'),
('subarray-divisible-k','Subarray Sums Divisible by K','https://leetcode.com/problems/subarray-sums-divisible-by-k/','Medium','Prefix Sum'),
('max-product-three','Maximum Product of Three Numbers','https://leetcode.com/problems/maximum-product-of-three-numbers/','Easy','Arrays'),
('find-pivot-index','Find Pivot Index','https://leetcode.com/problems/find-pivot-index/','Easy','Prefix Sum'),
('range-addition','Range Addition','https://leetcode.com/problems/range-addition/','Medium','Prefix Sum'),
('design-circular-queue','Design Circular Queue','https://leetcode.com/problems/design-circular-queue/','Medium','Queue'),
('number-of-recent-calls','Number of Recent Calls','https://leetcode.com/problems/number-of-recent-calls/','Easy','Queue'),
('implement-queue-stacks','Implement Queue using Stacks','https://leetcode.com/problems/implement-queue-using-stacks/','Easy','Queue'),
('shortest-path-binary-matrix','Shortest Path in Binary Matrix','https://leetcode.com/problems/shortest-path-in-binary-matrix/','Medium','BFS'),
('perfect-squares','Perfect Squares','https://leetcode.com/problems/perfect-squares/','Medium','BFS'),
('snakes-ladders','Snakes and Ladders','https://leetcode.com/problems/snakes-and-ladders/','Medium','BFS'),
('01-matrix','01 Matrix','https://leetcode.com/problems/01-matrix/','Medium','BFS'),
('as-far-land','As Far from Land as Possible','https://leetcode.com/problems/as-far-from-land-as-possible/','Medium','BFS'),
('keys-rooms','Keys and Rooms','https://leetcode.com/problems/keys-and-rooms/','Medium','DFS'),
('number-enclaves','Number of Enclaves','https://leetcode.com/problems/number-of-enclaves/','Medium','DFS'),
('flood-fill','Flood Fill','https://leetcode.com/problems/flood-fill/','Easy','DFS'),
('path-sum-iii','Path Sum III','https://leetcode.com/problems/path-sum-iii/','Medium','Trees'),
('sum-of-left-leaves','Sum of Left Leaves','https://leetcode.com/problems/sum-of-left-leaves/','Easy','Trees'),
('binary-tree-cameras','Binary Tree Cameras','https://leetcode.com/problems/binary-tree-cameras/','Hard','Trees'),
('recover-bst','Recover Binary Search Tree','https://leetcode.com/problems/recover-binary-search-tree/','Medium','Trees'),
('delete-node-bst','Delete Node in a BST','https://leetcode.com/problems/delete-node-in-a-bst/','Medium','Trees'),
('insert-bst','Insert into a Binary Search Tree','https://leetcode.com/problems/insert-into-a-binary-search-tree/','Medium','Trees'),
('convert-sorted-array-bst','Convert Sorted Array to Binary Search Tree','https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/','Easy','Trees'),
('balanced-bst','Balance a Binary Search Tree','https://leetcode.com/problems/balance-a-binary-search-tree/','Medium','Trees'),
('range-sum-bst','Range Sum of BST','https://leetcode.com/problems/range-sum-of-bst/','Easy','Trees'),
('all-paths-source-target','All Paths From Source Lead to Destination','https://leetcode.com/problems/all-paths-from-source-lead-to-destination/','Medium','Graphs'),
('course-schedule-ii','Course Schedule II','https://leetcode.com/problems/course-schedule-ii/','Medium','Graphs'),
('find-eventual-safe-states','Find Eventual Safe States','https://leetcode.com/problems/find-eventual-safe-states/','Medium','Graphs'),
('critical-connections','Critical Connections in a Network','https://leetcode.com/problems/critical-connections-in-a-network/','Hard','Graphs'),
('evaluate-division','Evaluate Division','https://leetcode.com/problems/evaluate-division/','Medium','Graphs'),
('accounts-merge','Accounts Merge','https://leetcode.com/problems/accounts-merge/','Medium','Graphs'),
('number-provinces','Number of Provinces','https://leetcode.com/problems/number-of-provinces/','Medium','Graphs'),
('min-height-trees','Minimum Height Trees','https://leetcode.com/problems/minimum-height-trees/','Medium','Graphs'),
('add-binary','Add Binary','https://leetcode.com/problems/add-binary/','Easy','Math'),
('valid-number','Valid Number','https://leetcode.com/problems/valid-number/','Hard','Math'),
('excel-sheet-column-number','Excel Sheet Column Number','https://leetcode.com/problems/excel-sheet-column-number/','Easy','Math'),
('excel-sheet-column-title','Excel Sheet Column Title','https://leetcode.com/problems/excel-sheet-column-title/','Easy','Math'),
('fizz-buzz','Fizz Buzz','https://leetcode.com/problems/fizz-buzz/','Easy','Arrays'),
('roman-to-integer','Roman to Integer','https://leetcode.com/problems/roman-to-integer/','Easy','Hash Map'),
('integer-to-roman','Integer to Roman','https://leetcode.com/problems/integer-to-roman/','Medium','Greedy'),
('string-to-integer-atoi','String to Integer (atoi)','https://leetcode.com/problems/string-to-integer-atoi/','Medium','Math'),
('longest-common-prefix','Longest Common Prefix','https://leetcode.com/problems/longest-common-prefix/','Easy','Strings'),
('find-index-first-occurrence','Find the Index of the First Occurrence in a String','https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/','Easy','Strings'),
('isomorphic-strings','Isomorphic Strings','https://leetcode.com/problems/isomorphic-strings/','Easy','Hash Map'),
('word-pattern','Word Pattern','https://leetcode.com/problems/word-pattern/','Easy','Hash Map'),
('group-shifted-strings','Group Shifted Strings','https://leetcode.com/problems/group-shifted-strings/','Medium','Hash Map'),
('longest-substring-two-distinct','Longest Substring with At Most Two Distinct Characters','https://leetcode.com/problems/longest-substring-with-at-most-two-distinct-characters/','Medium','Sliding Window'),
('minimum-window-subsequence','Minimum Window Subsequence','https://leetcode.com/problems/minimum-window-subsequence/','Hard','Sliding Window'),
('text-justification','Text Justification','https://leetcode.com/problems/text-justification/','Hard','Strings'),
('reverse-words-string','Reverse Words in a String','https://leetcode.com/problems/reverse-words-in-a-string/','Medium','Strings'),
('palindrome-partitioning-ii','Palindrome Partitioning II','https://leetcode.com/problems/palindrome-partitioning-ii/','Hard','Dynamic Programming'),
('string-compression','String Compression','https://leetcode.com/problems/string-compression/','Medium','Two Pointers'),
('find-all-duplicates-array','Find All Duplicates in an Array','https://leetcode.com/problems/find-all-duplicates-in-an-array/','Medium','Arrays'),
('first-missing-positive','First Missing Positive','https://leetcode.com/problems/first-missing-positive/','Hard','Arrays'),
('subarray-product-less-k','Subarray Product Less Than K','https://leetcode.com/problems/subarray-product-less-than-k/','Medium','Sliding Window'),
('maximum-average-subarray','Maximum Average Subarray I','https://leetcode.com/problems/maximum-average-subarray-i/','Easy','Sliding Window'),
('minimum-consecutive-cards','Minimum Consecutive Cards to Pick Up','https://leetcode.com/problems/minimum-consecutive-cards-to-pick-up/','Medium','Sliding Window'),
('intersection-arrays','Intersection of Two Arrays','https://leetcode.com/problems/intersection-of-two-arrays/','Easy','Hash Map'),
('intersection-arrays-ii','Intersection of Two Arrays II','https://leetcode.com/problems/intersection-of-two-arrays-ii/','Easy','Hash Map'),
('design-hashmap','Design HashMap','https://leetcode.com/problems/design-hashmap/','Easy','Hash Map'),
('design-hashset','Design HashSet','https://leetcode.com/problems/design-hashset/','Easy','Hash Map'),
('my-calendar-i','My Calendar I','https://leetcode.com/problems/my-calendar-i/','Medium','Intervals'),
('employee-free-time','Employee Free Time','https://leetcode.com/problems/employee-free-time/','Hard','Intervals'),
('interval-list-intersections','Interval List Intersections','https://leetcode.com/problems/interval-list-intersections/','Medium','Intervals'),
('minimum-number-arrows','Minimum Number of Arrows to Burst Balloons','https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/','Medium','Intervals'),
('wiggle-subsequence','Wiggle Subsequence','https://leetcode.com/problems/wiggle-subsequence/','Medium','Greedy'),
('lemonade-change','Lemonade Change','https://leetcode.com/problems/lemonade-change/','Easy','Greedy'),
('valid-parentheses-string','Valid Parenthesis String','https://leetcode.com/problems/valid-parenthesis-string/','Medium','Greedy'),
('partition-array-max-sum','Partition Array for Maximum Sum','https://leetcode.com/problems/partition-array-for-maximum-sum/','Medium','Dynamic Programming'),
('best-time-stock-with-cooldown','Best Time to Buy and Sell Stock with Cooldown','https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/','Medium','Dynamic Programming'),
('best-time-stock-fee','Best Time to Buy and Sell Stock with Transaction Fee','https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/','Medium','Dynamic Programming')
ON CONFLICT (id) DO NOTHING;
