package com.faangtracker;

import java.sql.Date;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.temporal.TemporalAdjusters;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/learning")
@CrossOrigin(origins = "http://localhost:3000")
public class LearningController {
  private final JdbcTemplate jdbc;
  public LearningController(JdbcTemplate jdbc) { this.jdbc = jdbc; }
  @GetMapping("/dashboard")
  public Map<String,Object> dashboard(){LocalDate today=LocalDate.now(),weekStart=today.with(TemporalAdjusters.previousOrSame(DayOfWeek.MONDAY)),monthStart=today.withDayOfMonth(1);Map<String,Object> o=new LinkedHashMap<>();o.put("totalMinutes",scalar("SELECT COALESCE(SUM(minutes),0) FROM study_session"));o.put("weekMinutes",scalar("SELECT COALESCE(SUM(minutes),0) FROM study_session WHERE session_date >= ?",Date.valueOf(weekStart)));o.put("monthMinutes",scalar("SELECT COALESCE(SUM(minutes),0) FROM study_session WHERE session_date >= ?",Date.valueOf(monthStart)));o.put("sessionCount",scalar("SELECT COUNT(*) FROM study_session"));o.put("bestDay",jdbc.queryForList("SELECT session_date,SUM(minutes) AS minutes FROM study_session GROUP BY session_date ORDER BY minutes DESC,session_date DESC LIMIT 1"));o.put("bySkill",jdbc.queryForList("SELECT track AS skill,SUM(minutes) AS minutes,COUNT(*) AS sessions,MAX(session_date) AS last_studied FROM study_session GROUP BY track ORDER BY minutes DESC"));o.put("weekBySkill",jdbc.queryForList("SELECT track AS skill,SUM(minutes) AS minutes FROM study_session WHERE session_date >= ? GROUP BY track ORDER BY minutes DESC",Date.valueOf(weekStart)));o.put("activity",jdbc.queryForList("SELECT session_date AS date,SUM(minutes) AS minutes FROM study_session WHERE session_date >= ? GROUP BY session_date ORDER BY session_date",Date.valueOf(today.minusDays(29))));o.put("growth",jdbc.queryForList("SELECT session_date AS date,track AS skill,minutes FROM study_session ORDER BY session_date,track"));o.put("weeklyTargetMinutes",600);o.put("streak",streak());return o;}
  @GetMapping("/skills/{skill}") public Map<String,Object> skill(@PathVariable String skill){Map<String,Object>o=new LinkedHashMap<>();o.put("skill",skill);o.put("summary",jdbc.queryForList("SELECT COALESCE(SUM(minutes),0) AS minutes,COUNT(*) AS sessions,MAX(session_date) AS last_studied FROM study_session WHERE track=?",skill));o.put("recent",jdbc.queryForList("SELECT id,session_date,minutes,notes FROM study_session WHERE track=? ORDER BY session_date DESC,id DESC LIMIT 100",skill));o.put("streak",skillStreak(skill));return o;}
  @GetMapping("/goals") public List<Map<String,Object>> goals(){return jdbc.queryForList("SELECT id,skill_name,target_outcome,deadline,weekly_minutes,created_at FROM learning_goal ORDER BY deadline NULLS LAST,id DESC");}
  @PostMapping("/goals") public ResponseEntity<?> createGoal(@RequestBody Map<String,Object>b){String skill=text(b.get("skillName")),outcome=text(b.get("targetOutcome"));if(skill==null||outcome==null)return ResponseEntity.badRequest().body(Map.of("error","skillName and targetOutcome are required"));if(skill.length()>50||outcome.length()>500)return ResponseEntity.badRequest().body(Map.of("error","skill or outcome is too long"));int weekly=number(b.get("weeklyMinutes"),0);if(weekly<0||weekly>10080)return ResponseEntity.badRequest().body(Map.of("error","weeklyMinutes must be between 0 and 10080"));String deadline=text(b.get("deadline"));jdbc.update("INSERT INTO learning_goal(skill_name,target_outcome,deadline,weekly_minutes) VALUES(?,?,?,?)",skill,outcome,deadline==null?null:Date.valueOf(deadline),weekly);return ResponseEntity.ok(Map.of("saved",true));}
  @DeleteMapping("/goals/{id}") public ResponseEntity<?> deleteGoal(@PathVariable long id){jdbc.update("DELETE FROM learning_goal WHERE id=?",id);return ResponseEntity.ok(Map.of("saved",true));}
  @GetMapping("/journal") public List<Map<String,Object>> journal(){return jdbc.queryForList("SELECT id,journal_date,skill_name,learned,built,difficult,revisit,resources FROM learning_journal ORDER BY journal_date DESC,id DESC LIMIT 100");}
  @PostMapping("/journal") public ResponseEntity<?> createJournal(@RequestBody Map<String,Object>b){String skill=text(b.get("skillName"));if(skill==null)return ResponseEntity.badRequest().body(Map.of("error","skillName is required"));String date=text(b.get("date"));String revisit=text(b.get("revisit"));Date journalDate=date==null?Date.valueOf(LocalDate.now()):Date.valueOf(date);jdbc.update("INSERT INTO learning_journal(journal_date,skill_name,learned,built,difficult,revisit,resources) VALUES(?,?,?,?,?,?,?)",journalDate,skill,text(b.get("learned")),text(b.get("built")),text(b.get("difficult")),revisit,text(b.get("resources")));if(revisit!=null)jdbc.update("INSERT INTO learning_review(skill_name,topic,source_type,source_id,due_date,status) VALUES(?,?,?,?,?,?)",skill,revisit,"JOURNAL",jdbc.queryForObject("SELECT MAX(id) FROM learning_journal",Long.class),journalDate.toLocalDate().plusDays(7),"DUE");return ResponseEntity.ok(Map.of("saved",true));}
  private Object scalar(String sql,Object...args){return jdbc.queryForObject(sql,Object.class,args);}private int number(Object o,int f){return o instanceof Number n?n.intValue():f;}private String text(Object o){if(!(o instanceof String s))return null;s=s.trim();return s.isBlank()?null:s;}
  private int streak(){List<LocalDate>d=jdbc.query("SELECT DISTINCT session_date FROM study_session ORDER BY session_date DESC",(rs,n)->rs.getDate(1).toLocalDate());if(d.isEmpty())return 0;LocalDate c=LocalDate.now();if(!d.get(0).equals(c))c=c.minusDays(1);int x=0;for(LocalDate v:d){if(!v.equals(c))break;x++;c=c.minusDays(1);}return x;}
  private int skillStreak(String skill){List<LocalDate>d=jdbc.query("SELECT DISTINCT session_date FROM study_session WHERE track=? ORDER BY session_date DESC",(rs,n)->rs.getDate(1).toLocalDate(),skill);if(d.isEmpty())return 0;LocalDate c=LocalDate.now();if(!d.get(0).equals(c))c=c.minusDays(1);int x=0;for(LocalDate v:d){if(!v.equals(c))break;x++;c=c.minusDays(1);}return x;}
}
