package com.faangtracker;

import java.sql.Date;
import java.time.LocalDate;
import java.util.*;
import org.springframework.http.ResponseEntity;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.bind.annotation.*;

@RestController
@RequestMapping("/api/phase3")
@CrossOrigin(origins="http://localhost:3000")
public class Phase3Controller {
 private final JdbcTemplate jdbc;
 public Phase3Controller(JdbcTemplate jdbc){this.jdbc=jdbc;}
 @GetMapping("/evidence") public List<Map<String,Object>> evidence(){return jdbc.queryForList("SELECT id,skill_name,title,evidence_type,description,url,project_id,verified,created_at FROM portfolio_evidence ORDER BY verified DESC,created_at DESC");}
 @PostMapping("/evidence") public ResponseEntity<?> add(@RequestBody Map<String,Object>b){String skill=text(b.get("skillName")),title=text(b.get("title")),type=text(b.get("evidenceType"));if(skill==null||title==null||type==null)return ResponseEntity.badRequest().body(Map.of("error","skillName, title and evidenceType are required"));if(skill.length()>50||title.length()>200||type.length()>50)return ResponseEntity.badRequest().body(Map.of("error","field too long"));jdbc.update("INSERT INTO portfolio_evidence(skill_name,title,evidence_type,description,url,project_id) VALUES(?,?,?,?,?,?)",skill,title,type,text(b.get("description")),text(b.get("url")),numberOrNull(b.get("projectId")));return ResponseEntity.ok(Map.of("saved",true));}
 @PatchMapping("/evidence/{id}") public ResponseEntity<?> verify(@PathVariable long id,@RequestBody Map<String,Object>b){jdbc.update("UPDATE portfolio_evidence SET verified=? WHERE id=?",Boolean.TRUE.equals(b.get("verified")),id);return ResponseEntity.ok(Map.of("saved",true));}
 @DeleteMapping("/evidence/{id}") public ResponseEntity<?> delete(@PathVariable long id){jdbc.update("DELETE FROM portfolio_evidence WHERE id=?",id);return ResponseEntity.ok(Map.of("saved",true));}
 @GetMapping("/search") public Map<String,Object> search(@RequestParam(defaultValue="") String q){String term="%"+q.trim().toLowerCase()+"%";List<Map<String,Object>> results=new ArrayList<>();results.addAll(jdbc.queryForList("SELECT id,'session' AS kind,track AS skill,COALESCE(notes,'') AS title,session_date AS date FROM study_session WHERE LOWER(track) LIKE ? OR LOWER(COALESCE(notes,'')) LIKE ? ORDER BY session_date DESC LIMIT 30",term,term));results.addAll(jdbc.queryForList("SELECT id,'journal' AS kind,skill_name AS skill,COALESCE(learned,'') AS title,journal_date AS date FROM learning_journal WHERE LOWER(skill_name) LIKE ? OR LOWER(COALESCE(learned,'')) LIKE ? OR LOWER(COALESCE(built,'')) LIKE ? ORDER BY journal_date DESC LIMIT 30",term,term,term));results.addAll(jdbc.queryForList("SELECT id,'project' AS kind,skill_name AS skill,name AS title,target_date AS date FROM learning_project WHERE LOWER(skill_name) LIKE ? OR LOWER(name) LIKE ? OR LOWER(COALESCE(outcome,'')) LIKE ? ORDER BY created_at DESC LIMIT 30",term,term,term));results.addAll(jdbc.queryForList("SELECT id,'evidence' AS kind,skill_name AS skill,title AS title,created_at AS date FROM portfolio_evidence WHERE LOWER(skill_name) LIKE ? OR LOWER(title) LIKE ? OR LOWER(COALESCE(description,'')) LIKE ? ORDER BY created_at DESC LIMIT 30",term,term,term));return Map.of("query",q,"results",results);}
 @GetMapping("/next") public Map<String,Object> next(){List<Map<String,Object>> skills=jdbc.queryForList("SELECT s.skill,COALESCE(SUM(ss.minutes),0) minutes,COALESCE(COUNT(ss.id),0) sessions FROM (SELECT DISTINCT track skill FROM study_session UNION SELECT name FROM custom_skill WHERE active=true UNION SELECT 'DSA' UNION SELECT 'Java' UNION SELECT 'System Design' UNION SELECT 'Distributed Systems' UNION SELECT 'JVM Performance' UNION SELECT 'AI Engineering') s LEFT JOIN study_session ss ON ss.track=s.skill GROUP BY s.skill ORDER BY minutes ASC,s.skill");Map<String,Object> recommendation=new LinkedHashMap<>();if(!skills.isEmpty()){Map<String,Object>x=skills.get(0);recommendation.put("skill",x.get("skill"));recommendation.put("reason","Lowest logged effort — increase depth here next.");recommendation.put("suggestedMinutes",120);}Long due=jdbc.queryForObject("SELECT COUNT(*) FROM learning_review WHERE status <> 'COMPLETED' AND due_date <= ?",Long.class,Date.valueOf(LocalDate.now()));Long projects=jdbc.queryForObject("SELECT COUNT(*) FROM learning_project WHERE status <> 'DONE'",Long.class);recommendation.put("reviewsDue",due);recommendation.put("activeProjects",projects);recommendation.put("action",due>0?"Clear one overdue review before adding new material.":projects==0?"Create a skill-connected project to produce evidence.":"Spend 120 minutes on the lowest-effort skill and produce one concrete artifact.");return recommendation;}
 private String text(Object o){if(!(o instanceof String s))return null;s=s.trim();return s.isBlank()?null:s;}private Object numberOrNull(Object o){return o instanceof Number?n(o):null;}private Long n(Object o){return ((Number)o).longValue();}
}
